### ISSUE TITLE
Add support for radial velocity data

### ISSUE THREAD

**Issue by sefffal** [sefffal/Octofitter.jl#2]
We would like to be able to support radial velocity data with the following requirements:
* Multiple instruments
* Instrument specific jitter
* Plotting support in the analysis file (`timeplot` and `timeplotgrid`)

We can implement this by creating a new subtype of AbstractObs (types.jl) and likelihood functions (models.jl)
Users can add an `rv` parameter to the system to model the unperturbed radial velocity.

We would like to be able to add rv data to both the system as a whole and to planets, so we will have to write two separate likelihood functions (they can share code though).

A nice bonus feature could be a helper function to read in the GAIA RV from the HGCA catalog that is already downloaded.

**Comment by sefffal** [comment]
Support for single instrument RV data now implemented.
Still todo: multiple instruments, docs, and recommendations for parameterization e.g. i=0, \Omega=0.

**Comment by Bhavesh012** [comment]
Is there a possibility to add the RV Data support in Octofitterpy too? Right now, I am experiencing this error:

`NameError: name 'OctofitterRadialVelocity' is not defined`

while defining RV likelihood in the demo notebook of octofitterpy:
```
rv_star_like = octo.StarAbsoluteRVLikelihood(
  epoch=[ 54899.5],
  # m/s, positive away from the observer
  rv = [1200],
  # m/s
  σ_rv = [1000],
  # Instrument number
  inst_idx = [1],
)
```

I found out that it arises from the function in the `python_interface.py` in octofitterpy:
```
def StarAbsoluteRVLikelihood(**data):
  for k,v in data.items():
      data[k] = jl_array(v)
  return jl.OctofitterRadialVelocity.StarAbsoluteRVLikelihood(Octofitter.Table(**data))
```

OctofitterRadialVelocity has been installed in the Julia environment during the testing.

**Comment by sefffal** [comment]
Hi @Bhavesh012 , I would be happy to investigate this. Let's open a new issue.
