### ISSUE TITLE
Issue using RV data with octofitterpy

### ISSUE THREAD

**Issue by sefffal** [sefffal/Octofitter.jl#41]
From @bhavesh012:

Hi, is there a possibility to add the RV Data support in Octofitterpy too? Right now, I am experiencing this error:

`NameError: name 'OctofitterRadialVelocity' is not defined`

while defining RV likelihood in the demo notebook of octofitterpy:
```
rv_star_like = octo.StarAbsoluteRVLikelihood(
  epoch=[ 54899.5],
  # m/s, positive away from the observer
  rv = [1200],
  # m/s
  σ_rv = [1000],
  # Instrument number
  inst_idx = [1],
)
```

I found out that it arises from the function in the `python_interface.py` in octofitterpy:
```
def StarAbsoluteRVLikelihood(**data):
  for k,v in data.items():
      data[k] = jl_array(v)
  return jl.OctofitterRadialVelocity.StarAbsoluteRVLikelihood(Octofitter.Table(**data))
```

OctofitterRadialVelocity has been installed in the Julia environment during the testing.

_Originally posted by @Bhavesh012 in https://github.com/sefffal/Octofitter.jl/issues/2#issuecomment-2310924774_

**Comment by sefffal** [comment]
Hi @bhavesh012, thank you for bringing this to our attention!
Could you tell us the version of octofitterpy that you are using?

**Comment by Bhavesh012** [comment]
Sure, the version is `'3.0.1'`. I just installed it last week so it should be the most recent build.

**Comment by sefffal** [comment]
Thank you! Could you try running the following:

```
octo.jl.seval("using OctofitterRadialVelocity")
```

Do you see any errors?

**Comment by Bhavesh012** [comment]
Ok, I did and it ran without errors.

**Comment by sefffal** [comment]
Thanks, that's good news. And if you run 

```
rv_star_like = octo.StarAbsoluteRVLikelihood(
  epoch=[ 54899.5],
  # m/s, positive away from the observer
  rv = [1200],
  # m/s
  σ_rv = [1000],
  # Instrument number
  inst_idx = [1],
)
```

could you please report the error message?

**Comment by Bhavesh012** [comment]
Here you go:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[13], line 1
----> 1 rv_star_like = octo.StarAbsoluteRVLikelihood(
      2     epoch=[ 54899.5],#, 55249.5, 57499.5],
      3     # m/s, positive away from the observer
      4     rv = [1200],#, 600, -900] ,
      5     # m/s
      6     σ_rv = [1000],#,1000,1000] ,
      7     # Instrument number
      8     inst_idx = [1],#, 1, 1],
      9 )

File ~/opt/anaconda3/envs/exo_orbit/lib/python3.10/site-packages/octofitterpy/python_interface.py:92, in StarAbsoluteRVLikelihood(**data)
     90 for k,v in data.items():
     91     data[k] = jl_array(v)
---> 92 return OctofitterRadialVelocity.StarAbsoluteRVLikelihood(Octofitter.Table(**data))

NameError: name 'OctofitterRadialVelocity' is not defined"
```

**Comment by sefffal** [comment]
Thank you! I see now the problem is that I didn't submit the latest version of the code to PyPI.

Eg see here: https://github.com/sefffal/octofitterpy/blob/cbfa4df54fe320bf45733cf703ddc20aff684c70/octofitterpy/python_interface.py#L90


I will do so now. Sorry about that!

**Comment by Bhavesh012** [comment]
Ah! I see. I naively tried putting `jl.seval("using OctofitterRadialVelocity")` in the function, but that didn't work out. Sorry, I am not adept at Julia yet. Thanks for quickly solving the issue though!

**Comment by sefffal** [comment]
Okay, I have submitted version 3.10.0 to PyPI. Please try upgrading the package, and hopefully this will be fixed.

**Comment by Bhavesh012** [comment]
Okay, thanks! I updated the package, and now the issue has been resolved! Thanks again! 😄

**Comment by sefffal** [comment]
That's excellent news! Please feel free to open an issue if you run into any trouble with your modelling. Best of luck!
