### ISSUE TITLE
Not able to retrieve planet properties

### ISSUE THREAD

**Issue by Bhavesh012** [sefffal/Octofitter.jl#45]
Hey, 

So, I got stuck while running the [Fit RV and Proper Motion Anomaly](https://sefffal.github.io/Octofitter.jl/dev/rv/#fit-rv-pma) notebook.

After defining the planet b and a system like this: 
```
@planet b Visual{KepOrbit} begin
    e = 0
    ω=0.0
    mass ~ Uniform(0, 3)
    a ~ truncated(Normal(3.48,0.1),lower=0)
    i ~ Sine()
    Ω ~ UniformCircular()

    τ ~ UniformCircular(1.0)
    P = √(b.a^3/system.M)
    tp =  b.τ*b.P*365.25 + 58849 
end

@system ϵEri begin
    M ~ truncated(Normal(0.78, 0.01),lower=0)
    plx ~ gaia_plx(;gaia_id)
    pmra ~ Normal(-975, 10)
    pmdec ~ Normal(20,  10)

    # Radial velocity zero point per instrument
    rv0 ~ Product([
        Normal(0,10), # m/s
        Normal(0,10),
    ])
    # Radial jitter per instrument.
    jitter ~ Product([
        truncated(Normal(0,10),lower=0), # m/s
        truncated(Normal(0,10),lower=0),
    ])
end HGCALikelihood(;gaia_id) rvs_merged b
```
and then while defining the model: `model = Octofitter.LogDensityModel(ϵEri )`

I get an error: `type Planet has no field a`.

This also comes up if I manually try to run `b.a` or `b.e`. So, the error is most probably coming when defining the period and tp in the planet, but I am not sure why. 

The error goes away if I manually set the prior for P and tp instead of calculating from pre-defined priors.

Running the latest version of Octofitter on Pluto.

**Comment by sefffal** [comment]
Hi @Bhavesh012 , thanks so much for the report. I wasn't able to reproduce this so far. Could you try sharing a complete example?

**Comment by Bhavesh012** [comment]
Hey @sefffal, for some reason, this issue is not occurring for me anymore. So, I think we are good.
