### ISSUE TITLE
Global Main._obs error in octofitterpy

### ISSUE THREAD

**Issue by krose098** [sefffal/Octofitter.jl#49]
Hi! 
I followed the instructions for python installation and then tried to run through the `demo.ipynb` notebook. 

When I reached this cell 

`planet_b = octo.Planet(
    name="b",
    basis="Visual{KepOrbit}",
    priors=
    """            
        a ~ LogUniform(0.1, 500)
        e ~ Uniform(0.0, 0.99)
        i ~ Sine()
        ω ~ UniformCircular()
        Ω ~ UniformCircular()
        θ ~ UniformCircular()
        tp = θ_at_epoch_to_tperi(system,b,50000) # use MJD epoch of your data here!!
    """,
    likelihoods=[astrom_like]
)`

I obtained an error which I'm unfamiliar with, which might be related to the Julia environment setup for the Jupyter notebook:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 1
----> 1 planet_b = octo.Planet(
      2     name="b",
      3     basis="Visual{KepOrbit}",
      4     priors=
      5     """            
      6         a ~ LogUniform(0.1, 500)
      7         e ~ Uniform(0.0, 0.99)
      8         i ~ Sine()
      9         ω ~ UniformCircular()
     10         Ω ~ UniformCircular()
     11         θ ~ UniformCircular()
     12         tp = θ_at_epoch_to_tperi(system,b,50000) # use MJD epoch of your data here!!
     13     """,
     14     likelihoods=[astrom_like]
     15 )

File /opt/homebrew/Cellar/jupyterlab/4.0.9_1/libexec/lib/python3.12/site-packages/octofitterpy/python_interface.py:43, in Planet(name, basis, priors, likelihoods)
     41 except:
     42     raise ValueError("likelihoods must be a list of likelihood objects (even if you are only providing one value)")
---> 43 jl.Main._obs = tuple(likelihoods)
     44 expr = f"""
     45     @planet {name} {basis} begin
     46         {priors}
     47     end (_obs...)
     48 """
     49 planet = jl.seval(expr)

File ~/.julia/packages/PythonCall/Nr75f/src/JlWrap/any.jl:254, in __setattr__(self, k, v)
    252     else:
    253         return
--> 254     self._jl_callmethod($(pyjl_methodnum(pyjlany_setattr)), k, v)
    255 def __dir__(self):
    256     return ValueBase.__dir__(self) + self._jl_callmethod($(pyjl_methodnum(pyjlany_dir)))

AttributeError: Julia: Global Main._obs does not exist and cannot be assigned. Declare it using `global` before attempting assignment.
`

Any help is appreciated. My main purpose in testing this package was to use Octofitter for RV fitting.

**Comment by sefffal** [comment]
Hi @krose098, sorry about that! I'll see if I can reproduce.

**Comment by sefffal** [comment]
My first guess is that for some reason pip installed the previous version of `octofitterpy`, and that picked up Julia 1.11 in the background (which isn't supported).

Could you confirm the following for me?

* the version of python you used
* the version of octofitterpy you installed via pip
* The version of Julia that was installed in the background:
```python
import octofitterpy as octo
octo.jl.VERSION
```


Those would really help in narrowing down the problem. Thanks very much!

**Comment by krose098** [comment]
Here's the output from running the snippet you sent `v"1.11.1"` ( the Julia version).

The octofitterpy version is `octofitterpy-5.0.0` and the Python version is `Python 3.12.4`.  If you need me to revert back to an earlier please let me know.

Thanks for the prompt reply!

**Comment by sefffal** [comment]
Thanks @krose098 ! So we have narrowed down the problem, version 1.11 of Julia was installed in the background when 1.10 should have been required.

As far as I understand, that shouldn't have happened. I will work to track it down.


Thanks for your help!

**Comment by krose098** [comment]
No problem! I'm happy to help and look forward to testing this further once you get a chance to track down the root issue.

Cheers!

**Comment by sefffal** [comment]
I released a new version that pins the Julia dependency to exactly 1.10.6. If you upgrade octofitterpy, it should hopefully work now.

If not, then I suspect there might be something specific to your setup that leads to this error (but to be clear, would still want to track down the root cause).

**Comment by krose098** [comment]
I ran `pip install -U octofitterpy` but was seeing that the Julia version was remaining 1.11 as before.
I tried to manually remove the Julia pkg files and then reinstall Julia but that seems to have caused an issue `ModuleNotFoundError: No module named 'juliacall'`

**Comment by sefffal** [comment]
In the past when I've needed to get a clean slate, I've been able to reinstall from scratch using:
```
pip uninstall juliacall octofitterpy
```

followed by 
```
pip install octofitterpy
```

It's odd that I'm not able to trigger the Julia 1.11 installation when I test.

**Comment by sefffal** [comment]
I wonder if you have a global installation of Julia 1.11 somewhere that is getting picked up for some reason.

**Comment by krose098** [comment]
I did attempt that clean slate approach to no avail. That was why I tried to manually remove the packages.

And as far as I know I do not have a global installation of Julia somewhere. I will continue to look for it though

**Comment by krose098** [comment]
Currently trying this on a remote machine to avoid any local dependency issues and it does appear to be installing Julia 1.10.6

**Comment by sefffal** [comment]
For your local PC, you could try the nuclear option and delete the `.julia` folder in your home folder.

E.g. on linux:
```
rm -rf ~/.julia
```

**Comment by krose098** [comment]
Even the nuclear option is still producing that error locally. Likely my fault for the way I tried to manually remove the Julia pkg files.

Running it remotely everything in the `demo.ipynb` notebook seems to be working nominally :)

**Comment by sefffal** [comment]
> Running it remotely everything in the demo.ipynb notebook seems to be working nominally :)

Okay, well I'm very glad to hear that part at least! Please let me know if you have any questions or run into any difficulties.

**Comment by krose098** [comment]
Thanks! Will do 👍

**Comment by sefffal** [comment]
In particular, if you only want to model RV (and not any astrometry data, proper motion data, etc) you might consider looking at these examples:

https://sefffal.github.io/Octofitter.jl/dev/rv-1/

**Comment by krose098** [comment]
Yes, I was looking at that originally. I will try to adapt that to Python

**Comment by sefffal** [comment]
@krose098  you might be interested to see these RV python examples I added today to the octofitterpy repo:

https://github.com/sefffal/octofitterpy/blob/master/examples/rv-examples.md

**Comment by krose098** [comment]
@sefffal these are very helpful, thank you!

**Comment by krose098** [comment]
I'm finding the model fitting to be quite sensitive to the priors. Is this normal or is it an issue that I'm using RVs from different spectral lines rather than RVs from different instruments? (This is for a stellar binary by the way, not an exoplanet system).

**Comment by krose098** [comment]
No worries. Thanks again for all of your help on this :)
